<#

.SYNOPSIS
This script generates and admin API key

.DESCRIPTION
The script needs to run locally on the Master server.
It will generate an admin API Key

.EXAMPLE
.\generateApiKey.ps1 -tenantId myTenant1 -apiKeyId myApiKeyId -outputFilePath 'C:\my file\Path\File.api'

#>

Param(
    [Parameter()]
    [string]$tenantId = "-",
    [Parameter()]
    [string]$apiKeyId,
    [Parameter()]
    [string]$outputFilePath = "C:\Program Files (x86)\Messaging Architects\Netmail WebAdmin\var\dbf\apikey.dat"
)

Set-Location $PSScriptRoot

$myDate = (Get-Date -f yyyyMMdd_hh_mm_ss).ToString()
$curlExe = "$env:NETMAIL_BASE_DIR\etc\scripts\setup\curl.exe"

if (!$apiKeyId) {
    $chars = [Char[]]'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
    $apiKeyId = (1..5 | ForEach-Object {'{0:X}' -f (Get-Random -InputObject $chars ) }) -join ''
}

$url = "https://localhost:444/$tenantId/apikeys"
$payLoad = @"
{
    "id": "$apiKeyId",
    "description": "Api key generated by getApiKey.ps1 on $myDate"
}
"@
$payLoad | Out-File .\temp.json -Encoding ascii

$curlParams = "-k -s -X POST -H 'Content-Type: application/json'"
$curlParams += " -H 'Accept: application/json'"
$curlParams += " -d `"@temp.json`" $url"
$apiKeyJson = (Invoke-Expression "& `"$curlExe`" $curlParams")
$apiKeyJson | Out-File ".\$($myDate)_apikey.json" -Encoding ascii
Write-Output "Response dumped to .\$($myDate)_apikey.json"
$apiKeyObj = @{}
($apiKeyJson -join "`n" | ConvertFrom-Json).psobject.properties | ForEach-Object { $apiKeyObj[$_.Name] = $_.Value }
$apiKeyObj['apikey'] | Out-File $outputFilePath -Encoding ascii
Write-Output "Api Key dumped to $outputFilePath"
return $apiKeyObj['apikey']